spring:
  config:
    import: "configserver:http://config-server:10220"
  cloud:
    config:
      uri: http://config-server:8888
      profile: test
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 6