spring:
  config:
    import: "configserver:http://server-config:10220"
  cloud:
    config:
      uri: http://server-config:8888
      profile: dev
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 6